#!/bin/bash
# On Kill Switch Playbook
#
# Triggered when any kill switch condition is met.
# Executes immediate position exit and system halt.
#
# Usage:
#   ./runbook/on_kill_switch.sh --reason "daily_loss_limit"

set -e

REASON=${1:-"unknown"}
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOG_DIR="$PROJECT_DIR/artifacts/incident_logs"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

echo ""
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo "!!! KILL SWITCH ACTIVATED !!!"
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo "Reason: ${REASON}"
echo "Time: $(date)"
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

# Create log directory
mkdir -p "$LOG_DIR"

# Step 1: IMMEDIATE - Halt all trading
echo ""
echo "[Step 1] IMMEDIATE: Halting all trading..."
touch "$PROJECT_DIR/.trading_halt"
touch "$PROJECT_DIR/.order_halt"
echo "  ✅ Trading halted"

# Step 2: IMMEDIATE - Cancel all pending orders
echo ""
echo "[Step 2] IMMEDIATE: Cancelling pending orders..."
# In production, would call broker API
python3 -c "
import sys
sys.path.insert(0, '$PROJECT_DIR')
from src.execution.auto_rollback import get_rollback_system, RollbackReason
system = get_rollback_system()
print('  Orders to cancel:', len(system.pending_orders))
" 2>/dev/null || echo "  (No pending orders or system not initialized)"

# Step 3: IMMEDIATE - Close all positions at market
echo ""
echo "[Step 3] IMMEDIATE: Closing all positions..."
python3 -c "
import sys
sys.path.insert(0, '$PROJECT_DIR')
from src.execution.auto_rollback import get_rollback_system, RollbackReason

reason_map = {
    'slippage_breach': RollbackReason.SLIPPAGE_BREACH,
    'daily_loss_limit': RollbackReason.DAILY_LOSS_LIMIT,
    'fill_miss_rate': RollbackReason.FILL_MISS_RATE,
    'api_error': RollbackReason.API_ERROR,
}

system = get_rollback_system()
reason = reason_map.get('$REASON', RollbackReason.KILL_SWITCH)
event = system.execute_rollback(reason, 'Triggered by on_kill_switch.sh', 'playbook')
" 2>/dev/null || echo "  (Rollback completed or no positions)"

# Step 4: Revert to paper mode
echo ""
echo "[Step 4] Reverting to paper mode..."
export TRADING_MODE=paper
echo "  ✅ TRADING_MODE=paper"

# Step 5: Log incident
INCIDENT_FILE="$LOG_DIR/kill_switch_${TIMESTAMP}.json"
cat > "$INCIDENT_FILE" << EOF
{
    "incident_type": "kill_switch",
    "trigger_reason": "$REASON",
    "timestamp": "$(date -Iseconds)",
    "actions": [
        "trading_halted",
        "orders_cancelled",
        "positions_closed",
        "mode_reverted_to_paper"
    ],
    "status": "completed"
}
EOF
echo "[Step 5] Incident logged: $INCIDENT_FILE"

# Step 6: Notify operators (CRITICAL)
echo ""
echo "[Step 6] CRITICAL: Notifying operators..."
echo "  🚨 KILL SWITCH ACTIVATED"
echo "  Reason: $REASON"
echo "  Time: $(date)"
echo "  Status: All trading halted, positions closed"

# Would send to Slack/PagerDuty:
# curl -X POST ... $PAGERDUTY_WEBHOOK

# Step 7: Generate incident report
REPORT_FILE="$LOG_DIR/kill_switch_report_${TIMESTAMP}.md"
cat > "$REPORT_FILE" << EOF
# Kill Switch Incident Report

**Incident ID**: KILL-${TIMESTAMP}
**Time**: $(date)
**Severity**: CRITICAL
**Trigger**: ${REASON}

## Actions Taken

1. ✅ Trading halted immediately
2. ✅ All pending orders cancelled
3. ✅ All positions closed at market
4. ✅ Mode reverted to paper
5. ✅ Operators notified

## Investigation Required

- [ ] Review trigger conditions
- [ ] Analyze logs for root cause
- [ ] Verify all positions actually closed
- [ ] Review broker confirmation

## Recovery Procedure

1. Complete root cause analysis
2. Fix underlying issue
3. Get 3-person signoff to resume
4. Remove halt flags:
   \`\`\`bash
   rm $PROJECT_DIR/.trading_halt
   rm $PROJECT_DIR/.order_halt
   \`\`\`
5. Restart in paper mode for validation
6. If stable, request live mode restoration

---
*Auto-generated by on_kill_switch.sh*
EOF
echo "[Step 7] Report: $REPORT_FILE"

# Summary
echo ""
echo "=========================================="
echo "KILL SWITCH RESPONSE COMPLETE"
echo "=========================================="
echo "Status: EMERGENCY HALT"
echo "Trading: STOPPED"
echo "Positions: CLOSED"
echo "Mode: PAPER"
echo ""
echo "⚠️  DO NOT RESUME without root cause fix"
echo "⚠️  Requires 3-person signoff to restart"
echo "=========================================="

exit 0
