#!/bin/bash
# On Slippage Breach Playbook
#
# Triggered when slippage exceeds modeled + 2σ
# Halts new order submission and notifies operators.
#
# Usage:
#   ./runbook/on_slippage_breach.sh --slippage 55 --threshold 50

set -e

SLIPPAGE=${1:-0}
THRESHOLD=${2:-50}
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOG_DIR="$PROJECT_DIR/artifacts/incident_logs"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

echo "=========================================="
echo "SLIPPAGE BREACH DETECTED"
echo "=========================================="
echo "Slippage: ${SLIPPAGE} bps"
echo "Threshold: ${THRESHOLD} bps"
echo "Time: $(date)"
echo "=========================================="

# Create log directory
mkdir -p "$LOG_DIR"

# Step 1: Halt new order submission
echo ""
echo "[Step 1] Halting new order submission..."
touch "$PROJECT_DIR/.order_halt"
echo "  Created halt flag: .order_halt"

# Step 2: Log incident
INCIDENT_FILE="$LOG_DIR/slippage_breach_${TIMESTAMP}.json"
cat > "$INCIDENT_FILE" << EOF
{
    "incident_type": "slippage_breach",
    "timestamp": "$(date -Iseconds)",
    "slippage_bps": $SLIPPAGE,
    "threshold_bps": $THRESHOLD,
    "breach_amount": $(echo "$SLIPPAGE - $THRESHOLD" | bc),
    "action_taken": "order_halt",
    "status": "investigating"
}
EOF
echo "[Step 2] Incident logged: $INCIDENT_FILE"

# Step 3: Notify operators (simulated)
echo ""
echo "[Step 3] Notifying operators..."
echo "  - Email: ops@example.com (simulated)"
echo "  - Slack: #trading-alerts (simulated)"
echo "  - SMS: On-call (simulated)"

# Would integrate with actual notification system:
# curl -X POST -H 'Content-type: application/json' \
#   --data '{"text":"🚨 SLIPPAGE BREACH: '${SLIPPAGE}' bps (threshold: '${THRESHOLD}'bps)"}' \
#   $SLACK_WEBHOOK_URL

# Step 4: Generate incident report
echo ""
echo "[Step 4] Generating incident report..."
REPORT_FILE="$LOG_DIR/slippage_incident_report_${TIMESTAMP}.md"
cat > "$REPORT_FILE" << EOF
# Slippage Breach Incident Report

**Incident ID**: SLIP-${TIMESTAMP}
**Time**: $(date)
**Severity**: HIGH

## Summary

Slippage of ${SLIPPAGE} bps detected, exceeding threshold of ${THRESHOLD} bps.

## Actions Taken

1. ✅ New order submission halted
2. ✅ Incident logged
3. ✅ Operators notified
4. ⏳ Awaiting investigation

## Next Steps

1. Review recent fills for anomalies
2. Check market conditions (volatility, liquidity)
3. Verify broker connectivity
4. Resume trading only after root cause identified

## Recovery

To resume trading:
\`\`\`bash
rm $PROJECT_DIR/.order_halt
\`\`\`

---
*Auto-generated by on_slippage_breach.sh*
EOF
echo "  Report: $REPORT_FILE"

# Summary
echo ""
echo "=========================================="
echo "INCIDENT RESPONSE COMPLETE"
echo "=========================================="
echo "Status: HALTED"
echo "Action Required: Manual review before resuming"
echo "Recovery: rm $PROJECT_DIR/.order_halt"
echo "=========================================="

exit 0
